arrowParens: avoid
bracketSameLine: false
bracketSpacing: true
endOfLine: lf
htmlWhitespaceSensitivity: css
insertPragma: false
jsxSingleQuote: false
printWidth: 100
proseWrap: preserve
quoteProps: as-needed
requirePragma: false
semi: false
singleQuote: true
tabWidth: 2
trailingComma: all
useTabs: false
